version: '3.0'

networks:
  haste-network:

volumes:
    haste-postgres:  

services:
  haste-server:
    build: .
    networks:
      - haste-network
    environment:
      - STORAGE_TYPE=postgres
      - STORAGE_HOST=pgsql
      - STORAGE_PORT=5432
    ports:
      - 7777:7777
  pgsql:
    image: postgres:10
    networks:
      - haste-network        
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hastedb
    volumes:
      - haste-postgres:/var/lib/postgresql/data
      - ./docker-entrypoint-initb.d/CreateDB.sql:/docker-entrypoint-initdb.d/CreateDB.sql:ro

